### ISSUE TITLE
Python error on some dynmaps

### ISSUE THREAD

**Issue by martinsik** [martinsik/minecraft-dynmap-timemachine#4]
Received the following issue in my inbox:

> Recently however I have a new error coming up and I am not sure how to solve it. I upgraded python to 3.7 now and I still receive the error below.
I was hoping you might have come across that and have a simple solution.

```
user@localhost:~/minecraft-dynmap-timemachine-master$ python3 ./dynmap-timemachine.py --list-worlds https://map.piratemc.com
Traceback (most recent call last):
  File "./dynmap-timemachine.py", line 46, in <module>
    dm = dynmap.DynMap(args.base_url)
  File "/home/blackbeard/minecraft-dynmap-timemachine-master/minecraft_dynmap_timemachine/dynmap.py", line 29, in __init__
    self._init()
  File "/home/blackbeard/minecraft-dynmap-timemachine-master/minecraft_dynmap_timemachine/dynmap.py", line 32, in _init
    for c in self.config['worlds']:
  File "/home/blackbeard/minecraft-dynmap-timemachine-master/minecraft_dynmap_timemachine/dynmap.py", line 75, in config
    self._config = json.loads(self._download_config())
  File "/home/blackbeard/minecraft-dynmap-timemachine-master/minecraft_dynmap_timemachine/dynmap.py", line 39, in _download_config
    rel_path = self.urls['configuration'].replace('{timestamp}', str(int(time.time())))
  File "/home/blackbeard/minecraft-dynmap-timemachine-master/minecraft_dynmap_timemachine/dynmap.py", line 63, in urls
    self._config_urls = self.parse_config_urls_string(self._download_config_urls())
  File "/home/blackbeard/minecraft-dynmap-timemachine-master/minecraft_dynmap_timemachine/dynmap.py", line 53, in parse_config_urls_string
    json_str = re.sub(pattern, repl, m.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by KerohiUa** [comment]
The same problem, and @yudegoma 's fix didn't help
